### ISSUE TITLE
Inserting internal links is broken

### ISSUE THREAD

**Issue by janno42** [fsr-de/1327#681]
When inserting internal links in the markdown editor, the link is added at the end of the document. It should be added at the current cursor position.

**Comment by Bartzi** [comment]
Note to myself: Seems that as Emojionearea spans its textarea and we are always copying the text of this textarea to the markdown edit textarea, we do not have the correct cursorposition anymore, hence we need to set this, we'll also need to make sure that the other buttons, which are broken as well, put the values into that text area...
