### ISSUE TITLE
Internal links break Markdown parsing

### ISSUE THREAD

**Issue by janno42** [fsr-de/1327#733]
When adding an internal link into a document, the content following the internal link in the same line is not rendered.
Content after an empty line is then again handled correctly.

**Comment by janno42** [comment]
@SilvanVerhoeven how are you getting along with this?

**Comment by gritfessel** [comment]
temporary fix is to add a `]` after the internal link. very weird

**Comment by janno42** [comment]
iirc, Silvan already had the correct fix for this issue but didn't push it :)

**Comment by gritfessel** [comment]
unbelievable :O
